Repository playframework/cachecontrol, pull requests merged in 2022-11, with the labels that each got.

#244 sbt 1.8.0-RC1
  project/build.properties
Labels: status:merge-when-green

#245 🔄 Synced file(s) with playframework/.github
  build.sbt
  common.sbt
  project/plugins.sbt
  scalastyle-config.xml
Labels: status:merge-when-green, sync

#247 sbt-java-formatter 0.8.0 (was 0.7.0)
  project/plugins.sbt
Labels: type:updates

#246 sbt-ci-release 1.5.11 (was 1.5.10)
  project/plugins.sbt
Labels: type:updates

#249 scala3-library 3.2.1 (was 3.2.0)
  project/Dependencies.scala
Labels: type:updates

#250 sbt 1.8.0 (was 1.8.0-RC1)
  project/build.properties
Labels: type:updates

#248 sbt-header 5.8.0 (was 5.7.0)
  project/plugins.sbt
Labels: status:merge-when-green, type:updates

#251 sbt-scalafmt 2.5.0 (was 2.4.6)
  project/plugins.sbt
Labels: type:updates
